version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run:
          name: First test
          command: npm test --  opposite-number
      - run:
          name: Second test
          command: npm test --  01.
      - run:
          name: Third test
          command: npm test --  02.
      - run:
          name: Fourth test
          command: npm test --  03.
      - run:
          name: Fifth test
          command: npm test --  04.
      - run:
          name: Sixth test
          command: npm test --  05.
      - run:
          name: Seventh test
          command: npm test --  06.
      - run:
          name: Eigth test
          command: npm test --  07.
      - run:
          name: All tests
          command: npm test
          
      
